app = "color-harmony-ai"
primary_region = "dfw"

[build]

[env]
  PORT = "8000"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  grace_period = "5s"
  method = "get"
  path = "/health"
  protocol = "http"
  timeout = "10s"
  tls_skip_verify = false

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "uploads_volume"
  destination = "/app/uploads"